REGIN_HOME_PATH=$(PROJECT_HOME)

TARGET_BIN=debug

REGIN_BIN_PATH=$(REGIN_HOME_PATH)/$(TARGET_BIN)
REGIN_SRC_PATH=$(REGIN_HOME_PATH)/src

LIB_PATH=$(REGIN_HOME_PATH)/../../lib/$(TARGET_BIN)

# Compiler setting
REGIN_CC=g++
REGIN_CFLAG=-Wall -g $(LOG_SETTING)

# Link setting
REGIN_LPP=g++
REGIN_LFLAG=

# Log setting
REGIN_LOG_TYPE=-D_STLOG_
REGIN_LOG_LEVEL=-DVERBOSE_LOG
#REGIN_LOG_LEVEL=-DL3_LOG
REGIN_LOG_SETTING=$(REGIN_LOG_TYPE) $(REGIN_LOG_LEVEL)


